version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-dependencies:
        patterns: ["*"]
        update-types: [minor, patch]
